### ISSUE TITLE
Please fix it

### ISSUE THREAD

**Issue by Lukmantj** [PANCHO7532/HCDecryptor#4]
I stuck in 
[ERROR] - Inexistent file path/name, aborting...
Please tell me, why do I always fail at this part

**Comment by PANCHO7532** [comment]
The path to the file should be always the last to write, i'll give you some examples:

node HCDecryptor.js /path/to/hc/file.hc

If you're on Windows and the file is on your desktop, then the command should be:

node HCDecryptor.js C:\Users\(username)\Desktop\file.hc

If you're on Linux and the file is on your Desktop

node HCDecryptor.js /home/(username)/Desktop/file.hc

(all of these examples are considering that your environment is in English, be sure to re-check the paths if they exist before writing)

And finally, if you're running Termux: 
First, you have to execute `termux-setup-storage` and accept the permissions that the app should request

Then, once accepted the permissions, let's say that the file that you are trying to decrypt is on your Download folder, then the command should be

node HCDecryptor /storage/emulated/0/Download/file.hc

or...

node HCDecryptor /sdcard/Download/file.hc

(replace "file.hc" by the filename of the file that you're trying to decrypt)

And that's all.

**Comment by PANCHO7532** [comment]
I'll close this issue considering that it may be solved now.
